# Generated by Django 4.2.2 on 2023-06-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.IntegerField(choices=[(1, 'Geral'), (2, 'Tecnologias'), (3, 'Cultura'), (4, 'Edcucacao')], default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
